//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cremeBrulee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeonDbEntities : DbContext
    {
        public LeonDbEntities()
            : base("name=LeonDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Carrito> tbl_Carrito { get; set; }
        public virtual DbSet<tbl_Cuenta> tbl_Cuenta { get; set; }
        public virtual DbSet<tbl_Direccion> tbl_Direccion { get; set; }
        public virtual DbSet<tbl_Inventario> tbl_Inventario { get; set; }
        public virtual DbSet<tbl_Orden> tbl_Orden { get; set; }
        public virtual DbSet<tbl_Producto> tbl_Producto { get; set; }
        public virtual DbSet<tbl_Usuario> tbl_Usuario { get; set; }
    }
}
