//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cremeBrulee
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Carrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Carrito()
        {
            this.tbl_Orden = new HashSet<tbl_Orden>();
        }
    
        public int CarritoID { get; set; }
        public int CuentaID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
    
        public virtual tbl_Cuenta tbl_Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Orden> tbl_Orden { get; set; }
    }
}
