//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cremeBrulee
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orden
    {
        public int OrdenID { get; set; }
        public int CuentaID { get; set; }
        public int CarritoID { get; set; }
        public System.DateTime FechaOrden { get; set; }
    
        public virtual tbl_Carrito tbl_Carrito { get; set; }
        public virtual tbl_Cuenta tbl_Cuenta { get; set; }
    }
}
